Feat/login backend
AderezosOrg/Web pull request #32
Opened 2024-10-20 21:08 UTC by OropezaHugo

create backend for login

2024-10-20 21:11 UTC, MayerliSantander requested changes

2024-10-20 21:11 UTC, MayerliSantander commented on backend/Controllers/LoginController.cs
> +}
Add endline

2024-10-20 21:11 UTC, MayerliSantander commented on backend/DTOs/WithoutId/LoginDTO.cs
> +}
Add endline

2024-10-20 21:11 UTC, MayerliSantander commented on backend/DTOs/WithoutId/SessionDTO.cs
> +}
Add endline

2024-10-20 21:11 UTC, MayerliSantander commented on backend/Services/LoginService.cs
> +}
Add endline

2024-10-20 21:11 UTC, MayerliSantander commented on backend/Services/ServicesInterfaces/ILoginService.cs
> +}
Add endline

2024-10-21 20:01 UTC, DeidamiaFuentes approved these changes

2024-10-21 20:13 UTC, MayerliSantander approved these changes

2024-10-21 20:14 UTC, merged